---
variables:
- group: "PipelineGrupoDeVariavel"
- name: PipelineLocalVariable
  value: 'Ola, sou uma variavel definida no pipeline'

#resources:
# repositories:
#   - repository: awesome
#     type: github
#     name: Hellkitezor/awesome
#     endpoint: Hellkitezor

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Pipeline-Definition.yaml

stages:
  - stage: Build
    displayName: Build
    jobs: 
      - job: JobUm
        displayName: Job Um
        pool:
          name: 'Default'
        steps:
        - script: |
            echo Tudo Certo, a etapa anterior foi aprovada e executada com sucesso.
            echo Neste momento vamos para o Deploy
#        - template: build.yml@the-awesome-templates
#          parameters:
#            parametroUm: $(PipelineVariableDentroDoGrupo)
#            parametroDois: ${{variables.PipelineLocalVariable}}
#            parametroTres: 'Sou um parametro que não veio de uma variavel de grupo nem de uma variavel local no pipeline'

  - stage: Deploy
    dependsOn: Build
    condition: succeeded()
    displayName: Deploy
    jobs:      
#      - deployment: DeployApproval
#       displayName: 'Approval Deploy To PRD'
#       environment: ApprovalGate

      - job: JobUm
        displayName: Job Dois
        pool:
          name: 'Default'
        steps:
        - script: |
            echo Tudo Certo, a etapa anterior foi aprovada e executada com sucesso.
            echo Neste momento vamos para o Deploy todos juntos
...
