---
variables:
- group: "PipelineGrupoDeVariavel"
- name: PipelineLocalVariable
  value: 'Ola, sou uma variavel definida no pipeline'

resources:
  repositories:
    - repository: Hellkitezor/awesome
      type: github
      name: Hellkitezor/awesome
      endpoint: ServiceConnectToGitHub

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - the-awesome-project/Pipeline-Definition.yaml

stages:
  - stage: Build
    displayName: Build
    jobs: 
      - job: JobUm
        displayName: Job Um
        pool:
          vmImage: 'windows-2019'
        steps:
        - template: build.yml@the-awesome-templates
          parameters:
            parametroUm: $(PipelineVariableDentroDoGrupo)
            parametroDois: ${{variables.PipelineLocalVariable}}
            parametroTres: 'Sou um parametro que não veio de uma variavel de grupo nem de uma variavel local no pipeline'

  - stage: Deploy
    dependsOn: Build
    condition: succeeded()
    displayName: Deploy
    jobs:      
      - deployment: DeployApproval
        displayName: 'Approval Deploy To PRD'
        environment: ApprovalGate

      - job: JobUm
        displayName: Job Dois
        pool:
          vmImage: 'windows-2019'
        steps:
        - script: |
            echo Tudo Certo, a etapa anterior foi aprovada e executada com sucesso.
            echo Neste momento vamos para o Deploy ;)
...
